### ISSUE TITLE
Option to update ChromeOS is gone?

### ISSUE THREAD

**Issue by qwertzguy** [WesBosch/brunch-toolkit#10]
I had toolkit 1.0.something installed and I remember I used it in the past to update ChromeOS version automatically, but I now updated to toolkit 3.0.5 and I can't figure out which option I should use to update my current installation?
When I select Install Brunch then follow through the options, it tells me it's going to wipe the hard drive. Isn't there a way to update ChromeOS like before? Without having to wipe everything

**Comment by WesBosch** [comment]
That option was removed due to a potential issue it caused, and is currently not planned as a better feature in brunch has replaced it quite well.

Please enable the PWA option and check out the information avaliable here, it is far better than what the toolkit could do before: https://github.com/sebanc/brunch/wiki/Brunch-PWA-Guide

**Comment by qwertzguy** [comment]
Ok thank you! I'll try the brunch pwa.
